on:
  push:
    paths:
      - .github/**
      - go.*
      - '**.go'
  pull_request:
    paths:
      - .github/**
      - go.*
      - '**.go'

name: Build

jobs:

  test:
    strategy:
      matrix:
        go-version: [ 1.15.x ]
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}

    steps:

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: go get
        run: go get

      - name: go build ./...
        run: go build ./...

      - name: go vet ./...
        run: go vet ./...

      - name: Test
        run: go test ./...

#    - name: golangci-lint
#      uses: golangci/golangci-lint-action@v2
#      with:
#        # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
#        version: v1.29
#
#        # Optional: working directory, useful for monorepos
#        # working-directory: somedir
#
#        # Optional: golangci-lint command line arguments.
#        # args: --issues-exit-code=0
#
#        # Optional: show only new issues if it's a pull request. The default value is `false`.
#        # only-new-issues: true
